/* 
  *   Speech.java generated by speechmod 
 */   

package scxmlgen.Modalities; 

import scxmlgen.interfaces.IModality; 

public enum Speech implements IModality{  

    S_LAZER("[lazer]", 1500),
    S_TRABALHO("[trabalho]", 1500),
    S_LOCK("[lock]", 1500),
    S_SCREENSHOT("[screenshot]", 1500),
    S_CAMERA("[camera]", 1500),
    S_BATERIA("[bateria]", 1500),
    S_WEBSITE("[website]", 1500),
    S_EMAIL("[email]", 1500),
    S_BRIGHTNESS_UP("[brightness_up]", 1500),
    S_BRIGHTNESS_DOWN("[brightness_down]", 1500),
    S_METEO("[meteo]", 1500),
    S_CALC("[calc]", 1500),
    S_NEXT_TRACK("[next_track]", 1500),
    S_PREVIOUS_TRACK("[previous_track]", 1500);

    private String event; 
    private int timeout;
    Speech(String m, int time) {
            event=m;
            timeout=time;
    }
    @Override
    public int getTimeOut(){
            return timeout;
    }
    @Override
    public String getEventName(){
            return event;
    }
    @Override
    public String getEvName(){
            return getModalityName().toLowerCase() +event.toLowerCase();
    }

}
